name: portfolio_mostafij
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.0
  hive: ^2.2.3
  intl: ^0.19.0
  shimmer: ^3.0.0
  go_router: ^13.0.1
  collection: ^1.18.0
  flutter_svg: ^2.0.9
  hive_flutter: ^1.1.0
  google_fonts: ^6.1.0
  json_annotation: ^4.8.1
  flutter_animate: ^4.4.0
  flutter_riverpod: ^2.4.9
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  freezed: ^2.4.6
  custom_lint: ^0.5.8
  build_runner: ^2.4.8
  riverpod_lint: ^2.3.7
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
